# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bb06c540d35b2629eef15c0f9e3f72b030ff741f6a5c8006486e8ef189bb155b56d785a719bad1e55b61f708c9f24d037cafcbc99b56d2516e7c057dedefb0b

test:
  secret_key_base: bf48d30b43f33905233999b7ce28fd0496ca0d31f0721b12a2046d9deddeefffc4fd05e613ae44c8513a38d917ade141c95f2c1feda6dce877db080e73e44e21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
